app/releases/models.py
class Release():		

	def __init__(self, releaseNumber, projectCount):		
		self.releaseNumber = releaseNumber
		self.projectCount = projectCount
		
class FilterOptionsReleases:

	def __init__(self, client, projectManager, status, sitCycle, devTeamLeader, testLead):

		self.client = client
		self.projectManager = projectManager
		self.status = status
		self.sitCycle = sitCycle
		self.devTeamLeader = devTeamLeader
		self.testLead = testLead
		
class Project():		

	def __init__(self, row):
		self.projectCode = row[0].strip()
		self.sitCycle = row[1]
		self.description = row[2]
		self.client = row[3]
		self.riskLevel = row[4]
		self.owner = row[5]
		self.projectManager = row[6]
		self.designer = row[7]
		self.deliveryManager = row[8]
		self.teamLeader = row[9]
		self.testLeader = row[10]
		self.productLeader = row[11]
		self.businessAnalyst = row[12]
		self.phase = row[13]
		self.notes = '<br>'.join(row[14][i:i+64] for i in range(0, len(row[14].strip()), 64))
		
class Client:

	def __init__(self, name, numberOfJobs = 0):
		self.name = name
		self.numberOfJobs = numberOfJobs
		
	def __eq__(self, other):
		return self.name == other.name
		
class ProjectManager:

	def __init__(self, name):
		self.name = name		

	def __eq__(self, other):
		return self.name == other.name
		
class DevTeamLead:

	def __init__(self, name):
		self.name = name		

	def __eq__(self, other):
		return self.name == other.name

class TestLead:

	def __init__(self, name):
		self.name = name		

	def __eq__(self, other):
		return self.name == other.name		

app/projects/views.py
from flask import Blueprint, render_template, request, url_for, redirect
import json

from app.projects.models import Project, Milestone, SoftwarePackage, Budget, Effort
from app.views import execute_query

mod = Blueprint('projects', __name__, url_prefix='/projects/')
	
@mod.route('<projectCode>')
def projectDetail(projectCode):

	sql = '''SELECT p1.procde, p1.desc, p1.client, COALESCE(risk.rag, 'G'), COALESCE(t1.tename, 'None'), COALESCE(t2.tename, 'None'), 
	                COALESCE(t3.tename, 'None'), COALESCE(t4.tename, 'None'), COALESCE(t5.tename, 'None'), COALESCE(t6.tename, 'None'), 
					COALESCE(t7.tename, 'None'), COALESCE(t8.tename, 'None'), p1.phase, p1.notes
			  FROM jhcjutil.project AS p1                                       
				LEFT OUTER JOIN tearner AS t1 ON p1.owner = t1.teear
				LEFT OUTER JOIN tearner AS t2 ON p1.manger = t2.teear
				LEFT OUTER JOIN tearner AS t3 ON p1.arctct = t3.teear
				LEFT OUTER JOIN tearner AS t4 ON p1.delvry = t4.teear
				LEFT OUTER JOIN tearner AS t5 ON p1.teamld = t5.teear
				LEFT OUTER JOIN tearner AS t6 ON p1.testld = t6.teear
				LEFT OUTER JOIN tearner AS t7 ON p1.prodld = t7.teear
				LEFT OUTER JOIN tearner AS t8 ON p1.anlyst = t8.teear
				LEFT OUTER JOIN (SELECT r2.procde AS procde,
									r2.entry,
									r2.rag AS rag,
									r2.summary AS summary,
									r2.notes AS notes
								FROM b6009822.jhcjutil.PROJRAG AS r2
								INNER JOIN (
									SELECT procde,
										max(entry) AS entry
									FROM b6009822.jhcjutil.PROJRAG
									GROUP BY procde
									) AS r3 ON r2.procde = r3.procde AND r2.entry = r3.entry) AS risk ON risk.procde = p1.procde	
			WHERE p1.procde = ? '''

	curs = execute_query(sql, parms = [projectCode])		
	data = curs.fetchall()

	project = Project(data[0])
	
	sql = '''SELECT milestone_desc, milestone_baseline, milestone_current, milestone_rag
				FROM project_milestones
			WHERE project_code = ?'''

	curs = execute_query(sql, parms = [projectCode])		
	data = curs.fetchall()				
		
	milestoneList = []
	
	for row in data:
		milestone = Milestone(row)
		milestoneList.append(milestone)
	
	sql = '''SELECT s.packno, s.app, s.status, s.drp2no, s.dripno 
			  FROM sofpack AS s                                
				INNER JOIN soflnk AS l ON s.packno = l.packno  
				INNER JOIN jobs3 AS j ON l.codex = j.codex     
			WHERE j.proj = ?  
			GROUP BY s.packno, s.app, s.status, s.drp2no, s.dripno
			ORDER BY s.packno'''
	
	curs = execute_query(sql, parms = [projectCode])		
	data = curs.fetchall()				
		
	softwarePackageList = []
	
	for row in data:
		softwarePackage = SoftwarePackage(row)
		softwarePackageList.append(softwarePackage)	
	
	sql = '''SELECT budget_type, budget_original, budget_revised, budget_actual, budget_forecast 
			  FROM budget                                  
			WHERE project_code = ?                             
			ORDER BY budget_type'''
	
	curs = execute_query(sql, parms = [projectCode])		
	data = curs.fetchall()				
		
	budgetList = []
	
	for row in data:
		budget = Budget(row)
		budgetList.append(budget)	
	
	sql = '''SELECT effort_type, effort_original, effort_revised, effort_actual, effort_forecast 
			  FROM effort                                  
			WHERE project_code = ?                             
			ORDER BY effort_type'''
	
	curs = execute_query(sql, parms = [projectCode])		
	data = curs.fetchall()				
		
	effortList = []
	
	for row in data:
		effort = Effort(row)
		effortList.append(effort)	
		
	return render_template("projects/detail.html", project=project, milestoneList=milestoneList, softwarePackageList=softwarePackageList, effortList=effortList, budgetList=budgetList, title="Projects")	
	

app/releases/views.py
from flask import Blueprint, render_template, request, url_for, redirect
from urllib import parse

from app.releases.models import Release, FilterOptionsReleases, Project, Client, ProjectManager, DevTeamLead, TestLead
from app.views import execute_query

mod = Blueprint('releases', __name__, url_prefix='/releases')

@mod.route('/')
def overview():

	sql = '''SELECT a.release_number, count(r.release_number)
			FROM jhcjutil.release_number_description AS a
				LEFT OUTER JOIN (SELECT r.release_number, r.project_code FROM jhcjutil.project AS p1                                       
								INNER JOIN jhcjutil.release_submissions_detail AS r             
										ON p1.procde = r.project_code						
							WHERE p1.status = 'ACTIVE'                                                            
							  AND r.release_committee_decision = 'APPROVED'
							  AND p1.closed <> 'Y'
							GROUP BY r.release_number, r.project_code) AS r ON a.release_number = r.release_number
			GROUP BY a.release_number
			ORDER BY a.release_number DESC'''

	curs = execute_query(sql)		
	data = curs.fetchall()

	releaseList = []
	
	for row in data:
		release = Release(row[0], row[1])
		releaseList.append(release)
		
	return render_template("releases/main.html", releaseList = releaseList, title="Releases")

@mod.route('/<release>')
def projectsByRelease(release):

	queryString = parse.unquote(request.query_string.decode("utf-8"))
	parameters = {}

	for parameter in queryString.split('&'):
		if "=" in parameter:
			parameters[parameter.split('=')[0]] = parameter.split('=')[1]

	client = parameters.get('client','')
	projectManager = parameters.get('projectmanager','')
	status = parameters.get('status','')
	sitCycle = parameters.get('sitcycle','')
	devTeamLeader = parameters.get('devteamleader','')
	testLead = parameters.get('testlead','')

	filterOptions = FilterOptionsReleases(client, projectManager, status, sitCycle, devTeamLeader, testLead)

	sql = '''SELECT p1.procde, r.sit_cycle, p1.desc, p1.client, COALESCE(risk.rag, 'G'), COALESCE(t1.tename, 'None'), COALESCE(t2.tename, 'None'), 
	                COALESCE(t3.tename, 'None'), COALESCE(t4.tename, 'None'), COALESCE(t5.tename, 'None'), COALESCE(t6.tename, 'None'), 
					COALESCE(t7.tename, 'None'), COALESCE(t8.tename, 'None'), p1.phase, p1.notes
			  FROM jhcjutil.project AS p1                                       
				INNER JOIN jhcjutil.release_submissions_detail AS r             
						ON p1.procde = r.project_code 
				LEFT OUTER JOIN tearner AS t1 ON p1.owner = t1.teear
				LEFT OUTER JOIN tearner AS t2 ON p1.manger = t2.teear
				LEFT OUTER JOIN tearner AS t3 ON p1.arctct = t3.teear
				LEFT OUTER JOIN tearner AS t4 ON p1.delvry = t4.teear
				LEFT OUTER JOIN tearner AS t5 ON p1.teamld = t5.teear
				LEFT OUTER JOIN tearner AS t6 ON p1.testld = t6.teear
				LEFT OUTER JOIN tearner AS t7 ON p1.prodld = t7.teear
				LEFT OUTER JOIN tearner AS t8 ON p1.anlyst = t8.teear
				LEFT OUTER JOIN (SELECT r2.procde AS procde,
									r2.entry,
									r2.rag AS rag,
									r2.summary AS summary,
									r2.notes AS notes
								FROM b6009822.jhcjutil.PROJRAG AS r2
								INNER JOIN (
									SELECT procde,
										max(entry) AS entry
									FROM b6009822.jhcjutil.PROJRAG
									GROUP BY procde
									) AS r3 ON r2.procde = r3.procde AND r2.entry = r3.entry) AS risk ON risk.procde = p1.procde											
			WHERE p1.status = 'ACTIVE'                                 
			  AND r.release_number = ?                            
			  AND r.release_committee_decision = 'APPROVED' 
			  AND p1.closed <> 'Y'
			GROUP BY p1.procde, r.sit_cycle, p1.desc, p1.client, risk.rag, t1.tename, t2.tename, t3.tename, t4.tename, t5.tename, t6.tename, t7.tename, t8.tename, p1.phase, p1.notes
			ORDER BY p1.procde                                         '''

	curs = execute_query(sql, parms = [release, ])		
	data = curs.fetchall()				
		
	projectList = []		
	clientList = []
	projectManagerList = []
	devTeamLeadList = []
	testLeadList = []
	
	for row in data:
	
		project = Project(row)
		projectList.append(project)
		
		if Client(project.client.strip()) not in clientList:
			client = Client(project.client.strip())
			clientList.append(client)

		if ProjectManager(project.projectManager.strip()) not in projectManagerList and project.projectManager.strip() != "":
			projectManager = ProjectManager(project.projectManager.strip())
			projectManagerList.append(projectManager)	

		if DevTeamLead(project.teamLeader.strip()) not in devTeamLeadList and project.teamLeader.strip() != "":
			devTeamLead = DevTeamLead(project.teamLeader.strip())
			devTeamLeadList.append(devTeamLead)
			
		if TestLead(project.testLeader.strip()) not in testLeadList and project.testLeader.strip() != "":
			testLead = TestLead(project.testLeader.strip())
			testLeadList.append(testLead)		
	
	projectManagerList = sorted(projectManagerList, key=lambda projectManager: projectManager.name)
	clientList = sorted(clientList, key=lambda client: client.name)
	
	return render_template("releases/list.html", projectList = projectList, clientList = clientList, filterOptions = filterOptions, projectManagerList = projectManagerList, devTeamLeadList=devTeamLeadList, testLeadList=testLeadList, title="Releases", release=release)
	

app/templates/releases/list.html
{% extends "base.html" %}{% block content %}

		<div class="filter container">
			<h1>{{release}}</h1>
			<form class="form-inline">
			  	<div class="form-group">
			    	<label for="status">Status</label>
			    	<select class="form-control" id="status">
					  	<option>All</option>
					  	<option {% if filterOptions.status == "R" %}selected {% endif %} value="R">Red</option>
					  	<option {% if filterOptions.status == "A" %}selected {% endif %} value="A">Amber</option>
					  	<option {% if filterOptions.status == "G" %}selected {% endif %} value="G">Green</option>
					</select>
			  	</div>			
			  	<div class="form-group">
			    	<label for="client">Client</label>
			    	<select class="form-control" id="client" value="{{filterOptions.client}}">
			    		<option>All</option>
						{% for client in clientList %}<option {% if client.name == filterOptions.client %}selected {% endif %}>{{client.name}}</option>{% endfor %}  	  	
					</select>
			  	</div>
			  	<div class="form-group">
			    	<label for="projectManager">Project Manager</label>
			    	<select class="form-control" id="projectmanager" value="{{filterOptions.projectManager}}">
			    		<option>All</option>
						{% for projectManager in projectManagerList %}<option {% if projectManager.name == filterOptions.projectManager %}selected {% endif %}>{{projectManager.name}}</option>{% endfor %}  	  	
					</select>
			  	</div>	
			  	<div class="form-group">
			    	<label for="sitcycle">SIT Cycle</label>
			    	<select class="form-control" id="sitcycle" value="{{filterOptions.sitCycle}}">
			    		<option>All</option>
						{% for sitCycle in ['SIT-1', 'SIT-2', 'SIT-3', 'SIT-4', 'Other'] %}<option {% if sitCycle == filterOptions.sitCycle %}selected {% endif %}>{{sitCycle}}</option>{% endfor %}  	  	
					</select>
			  	</div>	
			  	<div class="form-group">
			    	<label for="devTeamLeader">Dev Team Leader</label>
			    	<select class="form-control" id="devTeamLeader" value="{{filterOptions.devTeamLeader}}">
			    		<option>All</option>
						{% for devTeamLeader in devTeamLeadList %}<option {% if devTeamLeader.name == filterOptions.devTeamLeader %}selected {% endif %}>{{devTeamLeader.name}}</option>{% endfor %} 	  	
					</select>
			  	</div>	
			  	<div class="form-group">
			    	<label for="testLead">Test Leader</label>
			    	<select class="form-control" id="testLead" value="{{filterOptions.testLead}}">
			    		<option>All</option>
						{% for testLead in testLeadList %}<option {% if testLead.name == filterOptions.testLead %}selected {% endif %}>{{testLead.name}}</option>{% endfor %} 	  	
					</select>
			  	</div>					
			</form>
		</div>
	
		<div class="container">
			<div class="panel-group" id="accordion">	
				{% for sitCycle in ['SIT-1', 'SIT-2', 'SIT-3', 'SIT-4', 'Other'] %}
				<h2 class="sitheading" id="{{sitCycle}}">{{sitCycle}}</h2>
				{% for project in projectList if project.sitCycle == sitCycle or sitCycle =='Other' and project.sitCycle not in ['SIT-1', 'SIT-2', 'SIT-3', 'SIT-4'] %}
				<a href="{{url_for('projects.projectDetail', projectCode = project.projectCode)}}" class="panellink">
					<div class="panel panel-default {% if project.riskLevel == 'R' %}panel-danger{% endif %}{% if project.riskLevel == 'A' %}panel-warning{% endif %}{% if project.riskLevel == 'G' %}panel-success{% endif %}">
						<div class="panel-heading" id="H{{project.projectCode}}">					
							<h4 class="panel-title">				
								<span class="paneljobnumber">{{project.projectCode}}</span> - <span class="panelshorttext">{{project.description}}</span> - <span class="panelclient">{{project.client}}</span> 		
								<span class="panelstatus" style="display: none">{{project.riskLevel}}</span>							
							</h4>	
							<p>Project Manager: <span class="panelprojectmanager">{{project.projectManager}}</span></p>
							<p>Current Phase: {{project.phase}}</p>	
							<span class="panelsitcycle">{{project.sitCycle}}</span>	
							<span class="panelteamleader">{{project.teamLeader}}</span>	
							<span class="paneltestleader">{{project.testLeader}}</span>								
						</div>
				  </div>			
				</a>
				{% else %}
				<div class="panel panel-default">
						<div class="panel-heading" role="tab">
							<h4 class="panel-title">					        	
								Nothing is approved into this release yet.				        	
							</h4>
						</div>
				</div>								
				{% endfor %} 				
				{% endfor %}
			</div>
		</div>
	
		<script type="text/javascript">
		
		    function changeUrl(page, url) {
		        var obj = { Page: page, Url: url };
		        history.replaceState(obj, obj.Page, obj.Url);
		    }

			$.expr[":"].containsNoCase = function(el, i, m) {
			    var search = m[3];
			    if (!search) return false;
			    return new RegExp(search, "i").test($(el).text());
			};

			function filterList() {

				var status = $("#status").val();
				var client = $("#client").val();
				var projectManager = $("#projectmanager").val();
				var sitCycle = $("#sitcycle").val();
				var devTeamLeader = $("#devTeamLeader").val();
				var testLead = $("#testLead").val();								

				if (status == "All") {status = null};
				if (client == "All") {client = null};
				if (projectManager == "All") {projectManager = null};
				if (sitCycle === "All") {$(".sitheading").show()} else {$(".sitheading").hide(); $("#" + sitCycle).show()};
				if (sitCycle == "All") {sitCycle = null};
				if (devTeamLeader == "All") {devTeamLeader = null};
				if (testLead == "All") {testLead = null};				
				
		        $(".panellink").show();
				
		        var queryString = '';

				if (status) {$(".panelstatus").not(":containsNoCase(" + status + ")").parent().parent().parent().parent().hide();	queryString = queryString + '&status=' + status;};
		        if (projectManager) {$(".panelprojectmanager").not(":containsNoCase(" + projectManager + ")").parent().parent().parent().parent().hide();	queryString = queryString + '&projectmanager=' + projectManager;};
		        if (client) {$(".panelclient").not(":containsNoCase(" + client + ")").parent().parent().parent().parent().hide();	queryString = queryString + '&client=' + client;};					
				if (sitCycle) {$(".panelsitcycle").not(":containsNoCase(" + sitCycle + ")").parent().parent().parent().hide();	queryString = queryString + '&sitcycle=' + sitCycle;};	
				if (devTeamLeader) {$(".panelteamleader").not(":containsNoCase(" + devTeamLeader + ")").parent().parent().parent().hide();	queryString = queryString + '&devteamleader=' + devTeamLeader;};	
				if (testLead) {$(".paneltestleader").not(":containsNoCase(" + testLead + ")").parent().parent().parent().hide();	queryString = queryString + '&testlead=' + testLead;};	
				
		        if (queryString.length > 1) {queryString = '?' + encodeURIComponent(queryString.substring(1))} else {queryString = '?'};

		        changeUrl('Jobs 5', queryString);

			}

			$("#status").change(function() { filterList() });
			$("#projectmanager").change(function() { filterList() });
		    $("#client").change(function() { filterList() });
			$("#sitcycle").change(function() { filterList() });
			$("#devTeamLeader").change(function() { filterList() });
			$("#testLead").change(function() { filterList() });
			
			$( document ).ready(filterList());

		</script>
		
{% endblock %}

app/templates/releases/main.html
{% extends "base.html" %}{% block content %}
	
	<div class="container">
		<h1>Releases</h1>
		<div class="row">
			<div class="panel-group" id="accordion">		
				{% for release in releaseList %}		
				<a href="{{url_for('releases.projectsByRelease', release = release.releaseNumber)}}">	
					<div class="panel panel-default panel-success">			
							<div class="panel-heading">
								<h4 class="panel-title">					        	
									{{release.releaseNumber}} - {{release.projectCount}} Projects				        	
								</h4>
							</div>	
					</div>	
				</a>
				{% endfor %} 
			</div>	
		</div>
	</div>

{% endblock %}