app/files/models.py
import json

from app.views import execute_query
from app.models import MyEncoder

class Table():

	def __init__(self, library, table):
		self.library = library.upper()
		self.table = table.upper()
		
		curs = execute_query('SELECT * FROM (SELECT row_number() over () as rownum, rrn(a) AS rrn, a.* FROM ' + library.upper() + '.' + table.upper() + ' AS a) AS b ')	
		self.columns = [column[0] for column in curs.description]
		
	def data(self, firstRecord, pageSize, searchColumns, sortColumn, sortDirection, numberOfColumns, sEcho):
	
		# Unfiltered Record Count
		curs = execute_query('SELECT count(*) FROM ' + self.library + '.' + self.table)
		unfilteredRecordCount = curs.fetchone()[0]
		
		# Start building the SQL query
		sql = ' FROM (SELECT row_number() over () as rownum, rrn(a) AS rrn, a.* FROM '
		sql = sql + self.library + '.' + self.table + ' AS a WHERE 1=1'

		for key, value in searchColumns.items():
			sql = sql + ' AND UPPER(CAST(' + self.columns[key] + " AS char(5000))) LIKE ('%" + value.upper() + "%') "		
		
		# Filtered Record Count
		curs = execute_query('Select count(*) ' + sql + ') AS b')
		filteredRecordCount = curs.fetchone()[0]
		
		# Restrict to just a single page of data at a time
		sql = sql + ') AS b WHERE b.rownum BETWEEN ' + str(firstRecord) + ' AND ' + str(firstRecord + pageSize - 1)
		
		if sortColumn:
			sql = sql + ' ORDER BY ' + str(sortColumn) 
			sql = sql + ' ' + sortDirection	
		
		sql = sql + ' OPTIMIZE FOR ' + str(pageSize) + ' ROWS'	
			
		curs = execute_query('Select * ' + sql)
		data = curs.fetchall()	
	
		# Build the dictionary that we'll eventually collapse into JSON
		output = {}
		output['sEcho'] = sEcho
		output['iTotalRecords'] = str(unfilteredRecordCount)
		output['iTotalDisplayRecords'] = str(filteredRecordCount)	
		
		output['aaData'] = []
		
		for row in data:	
			for idx, value in enumerate(row):
				if value is None:
					row[idx] = 'Null'
			output['aaData'].append(list(row))

		return json.dumps(output, cls = MyEncoder)

app/files/views.py
from flask import Blueprint, url_for, redirect, render_template, request, flash
from app.files.models import Table

mod = Blueprint('files', __name__, url_prefix='/files/')

@mod.route('/', methods=['POST', 'GET'])
def overview():
		
	if 'library' in request.form:
		library=request.form['library']
	else:
		library = None
		
	if 'file' in request.form:
		file=request.form['file']
	else:
		file = None		
		
	if request.method == 'POST' and library and file:
		return redirect(url_for('files.view', library = library, table = file))
	elif request.method == 'POST':
		flash('Please enter both a library and file name')
		
	return render_template("files/overview.html", title= 'Files', library=library, file=file)	

@mod.route('<library>/<table>/')
def view(library, table):

	try:	
		tableInstance = Table(library, table)
	except:
		flash('This table does not exist')
		return redirect(url_for('files.overview'))
	
	return render_template("files/main.html", columns = tableInstance.columns, library = library, table = table, title= 'Files')		
	
@mod.route('<library>/<table>/data')
def get_data(library, table):			
		 	
	sEcho           = request.args.get('sEcho')		
	firstRecord     = int(request.args.get('iDisplayStart')) + 1
	pageSize        = int(request.args.get('iDisplayLength'))
	sortColumn      = int(request.args.get('iSortCol_0')) + 1
	sortDirection   = request.args.get('sSortDir_0')
	numberOfColumns = int(request.args.get('iColumns'))
	
	searchColumns = {}
	for i in range (0,numberOfColumns):
		if request.args.get('sSearch_' + str(i)) != '':
			searchColumns[i] = request.args.get('sSearch_' + str(i))
			
	table = Table(library, table)
	
	return table.data(firstRecord, pageSize, searchColumns, sortColumn, sortDirection, numberOfColumns, sEcho)	

app/templates/files/main.html
{% extends "base.html" %}{% block content %}
	
	{% with messages = get_flashed_messages() %}{% if messages %}
		<ul class="flashes alert alert-danger">{% for message in messages %}
			<li>{{ message }}</li>{% endfor %}
		</ul>{% endif %}
	{% endwith %}		
	
		<table id="main_table" class="table table-striped table-hover">
		
			<thead class="orange">
			  <tr>  
				{% for column in columns %}<th>{{column}}</th>{% endfor %}
			  </tr>
			</thead>	
			
			<tfoot>
			  <tr>  
				{% for column in columns %}<td>{{column}}</td>{% endfor %}
			  </tr>
			</tfoot>
			
			<tbody >

			</tbody>

		</table>

	
	<script> 
			$(document).ready(function() {
			var oTable = $('#main_table').dataTable( {
				"processing": true,
				"serverSide": true,
				"bStateSave": true,
				"dom": '<"top"ip><"right"lT>rt<"bottom"><"clear">',
				"sPaginationType": "full_numbers",
				"sScrollX": "100%",
				"tableTools": {"sSwfPath": "{{ url_for('static', filename='copy_csv_xls_pdf.swf') }}", "aButtons": [ "copy", "csv" ]},
				"sAjaxSource": "{{url_for('files.get_data', library = library, table = table)}}"
			} ).columnFilter({"bUseColVis": true});
			
			oTable.fnSetColumnVis( 0, false );
			oTable.fnSetColumnVis( 1, false );
			
			$('.text_filter').attr("value", "");
			$('.search_init').attr("value", "");
			
		} );		
	</script>
{% endblock %}	

app/templates/files/overview.html
{% extends "base.html" %}{% block content %}

		<div class="container">
			<h1>View file</h1>
			<form role="form" action="" method="POST">
				<div class="form-group">
					<label for="library">Library:</label>
					<input type="text" class="form-control" id="library" name="library" {% if library %}value="{{library}}"{% endif %}>
				  </div>
				  <div class="form-group">
					<label for="file">File:</label>
					<input type="text" class="form-control" id="file" name="file" {% if file %}value="{{file}}"{% endif %}>
				  </div>
				  <button type="submit" class="btn btn-default">Open</button>
			</form>
		</div>

{% endblock %}	