app/revenue/models.py
class Project():		

	def __init__(self, row):
		self.projectCode = row[0].strip()
		self.description = row[1]
		self.client = row[2]
		self.riskLevel = row[3]
		self.owner = row[4]
		self.projectManager = row[5]
		self.designer = row[6]
		self.deliveryManager = row[7]
		self.teamLeader = row[8]
		self.testLeader = row[9]
		self.productLeader = row[10]
		self.businessAnalyst = row[11]
		self.phase = row[12]
		self.notes = '<br>'.join(row[13][i:i+64] for i in range(0, len(row[13].strip()), 64))

class Milestone():		

	def __init__(self, row):
		self.description = row[0]
		self.baseline = row[1]
		self.current = row[2]
		self.riskLevel = row[3]

class SoftwarePackage():

	def __init__(self, row):
		self.number = row[0]
		self.application = row[1]
		self.status = row[2]
		self.approvedRelease = row[3]
		self.actualRelease = row[4]		

class Budget():

	def __init__(self, row):
		self.type = row[0]
		self.original = u"\xA3{:,.0f}".format(row[1])
		self.revised = u"\xA3{:,.0f}".format(row[2])
		self.actual = u"\xA3{:,.0f}".format(row[3])	
		self.forecast = u"\xA3{:,.0f}".format(row[4])
	
class Effort():

	def __init__(self, row):
		self.type = row[0]
		self.original = row[1]
		self.revised = row[2]
		self.actual = row[3]	
		self.forecast = row[4]
		
class Release():		

	def __init__(self, releaseNumber, projectCount):		
		self.releaseNumber = releaseNumber
		self.projectCount = projectCount

app/revenue/forms.py
from wtforms import TextField, SelectField, validators, DecimalField
from flask.ext.wtf import Form
from app.views import execute_query

class RevenueForm(Form):
	client = SelectField('Client', [validators.Required()])
	project = SelectField('Project')
	year = SelectField('Year', [validators.Required()])
	month = SelectField('Month', [validators.Required()])
	value = DecimalField('Value', [validators.Required()], places=2, default=0)
	
	def __init__(self, *args, **kwargs):
		super(RevenueForm, self).__init__(*args, **kwargs)	
	
		results = execute_query('''SELECT id, name
									FROM wapr.jhc_client
								ORDER BY name''')
		
		self.client.choices = [(result.id, result.name) for result in results.fetchall()]
		
		results = execute_query('''SELECT procde, desc                                               
								  FROM project                                                    
								WHERE status NOT IN ('COMPLETE', 'DROPPED', 'REJECT', 'CANCELLED',
													 'REJECTED')                                  
								ORDER BY procde''')
								
		self.project.choices = [("", "")]
		self.project.choices += [(result.procde, result.procde + ' - ' + result.desc) for result in results.fetchall()]
		self.year.choices = [("2016", "2016"), ("2017", "2017"), ("2018", "2018")]
		self.month.choices = [(str(i + 1), str(i + 1)) for i in range(12)]

app/revenue/views.py
from flask import Blueprint, render_template, request, url_for, redirect, flash
import json

from app.revenue.forms import RevenueForm
from app.revenue.api import *

mod = Blueprint('revenue', __name__, url_prefix='/revenue/')
	
@mod.route('/')
def detail():
	
	return render_template("revenue/detail.html", title="Revenue", revenueList = getAllRevenueEntries())	
	
@mod.route('summarybymonth')
def summaryByMonth():
	
	return render_template("revenue/summary_by_month.html", title="Revenue", revenueSummaryList = getSummaryByMonth())		
	
@mod.route('summarybyyear')
def summaryByYear():
	
	return render_template("revenue/summary_by_year.html", title="Revenue", revenueSummaryList = getSummaryByYear())	
	
@mod.route('add', methods=['GET','POST'])
def add():

	form = RevenueForm()
	
	if request.method == 'POST' and form.validate():
	
		client = form.client.data
		project = form.project.data
		year = form.year.data
		month = form.month.data
		value = form.value.data
			
		createRevenueEntry(client, project, year, month, value)
		flash('Created', 'success')	
		return redirect(url_for('revenue.detail'))
	
	return render_template("miForm.html", title="Revenue", form=form)		
	

app/templates/revenue/detail.html
{% extends "miBase.html" %}{% block content %}
	
	<div class="container">
	
		<div class="row">
		
			<a href="{{url_for('revenue.add') }}" class="floatleft">Add</a>
	
			<table id="main_table" class="table table-striped table-bordered">
			
				<thead>
					<tr>
						<th>Client</th>
						<th>Project</th>
						<th>Year</th>
						<th>Month</th>
						<th>Value</th>
					</tr>
				</thead>

				<tfoot>
					<tr>
						<th>Client</th>
						<th>Project</th>
						<th>Year</th>
						<th>Month</th>
						<th>Value</th>
					</tr>
				</tfoot>		
				
				<tbody>
				   
					{% for entry in revenueList %}
					<tr>
						<td>{{ entry.name }}</td>
						<td>{{ entry.project_code }} {% if entry.desc %} - {% endif %} {{ entry.desc }}</td>
						<td>{{ entry.year }}</td>
						<td>{{ entry.month }}</td>
						<td>{{ entry.value }}</td>
					</tr>	
					{% endfor %}
					
				</tbody>
				
			</table>

		</div>
		
			<script>
				$(document).ready(function() {
					$('#main_table').DataTable( {
						"iDisplayLength": 50,
						stateSave: true,
						initComplete: function () {
							this.api().columns().every( function () {
								var column = this;
								var select = $('<select><option value=""></option></select>')
									.appendTo( $(column.footer()).empty() )
									.on( 'change', function () {
										var val = $.fn.dataTable.util.escapeRegex(
											$(this).val()
										);
				 
										column
											.search( val ? '^'+val+'$' : '', true, false )
											.draw();
									} );
				 
								column.data().unique().sort().each( function ( d, j ) {
									var strippedValue = d.replace(/\<.*?\>\s?/g, '');
									select.append( '<option value="'+strippedValue+'">'+strippedValue+'</option>' )
								} );
							} );
						}
					} );
				} );
			</script>

	</div>

{% endblock %}

app/templates/revenue/summary_by_month.html
{% extends "miBase.html" %}{% block content %}
	
	<div class="container">
	
		<div class="row">
	
			<table id="main_table" class="table table-striped table-bordered">
			
				<thead>
					<tr>
						<th>Client</th>
						<th>Year</th>
						<th>Month</th>
						<th>Total Value</th>
					</tr>
				</thead>

				<tfoot>
					<tr>
						<th>Client</th>
						<th>Year</th>
						<th>Month</th>
						<th>Total Value</th>
					</tr>
				</tfoot>		
				
				<tbody>
				   
					{% for entry in revenueSummaryList %}
					<tr>
						<td>{{ entry.name }}</td>
						<td>{{ entry.year }}</td>
						<td>{{ entry.month }}</td>
						<td>{{ entry.total_value }}</td>
					</tr>	
					{% endfor %}
					
				</tbody>
				
			</table>

		</div>
		
			<script>
				$(document).ready(function() {
					$('#main_table').DataTable( {
						"iDisplayLength": 50,
						stateSave: true,
						initComplete: function () {
							this.api().columns().every( function () {
								var column = this;
								var select = $('<select><option value=""></option></select>')
									.appendTo( $(column.footer()).empty() )
									.on( 'change', function () {
										var val = $.fn.dataTable.util.escapeRegex(
											$(this).val()
										);
				 
										column
											.search( val ? '^'+val+'$' : '', true, false )
											.draw();
									} );
				 
								column.data().unique().sort().each( function ( d, j ) {
									var strippedValue = d.replace(/\<.*?\>\s?/g, '');
									select.append( '<option value="'+strippedValue+'">'+strippedValue+'</option>' )
								} );
							} );
						}
					} );
				} );
			</script>

	</div>

{% endblock %}

app/templates/revenue/summary_by_year.html
{% extends "miBase.html" %}{% block content %}
	
	<div class="container">
	
		<div class="row">
	
			<table id="main_table" class="table table-striped table-bordered">
			
				<thead>
					<tr>
						<th>Client</th>
						<th>Year</th>
						<th>Total Value</th>
					</tr>
				</thead>

				<tfoot>
					<tr>
						<th>Client</th>
						<th>Year</th>
						<th>Total Value</th>
					</tr>
				</tfoot>		
				
				<tbody>
				   
					{% for entry in revenueSummaryList %}
					<tr>
						<td>{{ entry.name }}</td>
						<td>{{ entry.year }}</td>
						<td>{{ entry.total_value }}</td>
					</tr>	
					{% endfor %}
					
				</tbody>
				
			</table>

		</div>
		
			<script>
				$(document).ready(function() {
					$('#main_table').DataTable( {
						"iDisplayLength": 50,
						stateSave: true,
						initComplete: function () {
							this.api().columns().every( function () {
								var column = this;
								var select = $('<select><option value=""></option></select>')
									.appendTo( $(column.footer()).empty() )
									.on( 'change', function () {
										var val = $.fn.dataTable.util.escapeRegex(
											$(this).val()
										);
				 
										column
											.search( val ? '^'+val+'$' : '', true, false )
											.draw();
									} );
				 
								column.data().unique().sort().each( function ( d, j ) {
									var strippedValue = d.replace(/\<.*?\>\s?/g, '');
									select.append( '<option value="'+strippedValue+'">'+strippedValue+'</option>' )
								} );
							} );
						}
					} );
				} );
			</script>

	</div>

{% endblock %}