app/releases/views.py
from flask import Blueprint, render_template, request, url_for, redirect
from urllib import parse

from app.releases.models import Release, FilterOptionsReleases, Project, Client, ProjectManager, DevTeamLead, TestLead
from app.views import execute_query

mod = Blueprint('releases', __name__, url_prefix='/releases')

@mod.route('/')
def overview():

	sql = '''SELECT a.release_number, count(r.release_number)
			FROM jhcjutil.release_number_description AS a
				LEFT OUTER JOIN (SELECT r.release_number, r.project_code FROM jhcjutil.project AS p1                                       
								INNER JOIN jhcjutil.release_submissions_detail AS r             
										ON p1.procde = r.project_code						
							WHERE p1.status = 'ACTIVE'                                                            
							  AND r.release_committee_decision = 'APPROVED'
							  AND p1.closed <> 'Y'
							GROUP BY r.release_number, r.project_code) AS r ON a.release_number = r.release_number
			GROUP BY a.release_number
			ORDER BY a.release_number DESC'''

	curs = execute_query(sql)		
	data = curs.fetchall()

	releaseList = []
	
	for row in data:
		release = Release(row[0], row[1])
		releaseList.append(release)
		
	return render_template("releases/main.html", releaseList = releaseList, title="Releases")

@mod.route('/<release>')
def projectsByRelease(release):

	queryString = parse.unquote(request.query_string.decode("utf-8"))
	parameters = {}

	for parameter in queryString.split('&'):
		if "=" in parameter:
			parameters[parameter.split('=')[0]] = parameter.split('=')[1]

	client = parameters.get('client','')
	projectManager = parameters.get('projectmanager','')
	status = parameters.get('status','')
	sitCycle = parameters.get('sitcycle','')
	devTeamLeader = parameters.get('devteamleader','')
	testLead = parameters.get('testlead','')

	filterOptions = FilterOptionsReleases(client, projectManager, status, sitCycle, devTeamLeader, testLead)

	sql = '''SELECT p1.procde, r.sit_cycle, p1.desc, p1.client, COALESCE(risk.rag, 'G'), COALESCE(t1.tename, 'None'), COALESCE(t2.tename, 'None'), 
	                COALESCE(t3.tename, 'None'), COALESCE(t4.tename, 'None'), COALESCE(t5.tename, 'None'), COALESCE(t6.tename, 'None'), 
					COALESCE(t7.tename, 'None'), COALESCE(t8.tename, 'None'), p1.phase, p1.notes
			  FROM jhcjutil.project AS p1                                       
				INNER JOIN jhcjutil.release_submissions_detail AS r             
						ON p1.procde = r.project_code 
				LEFT OUTER JOIN tearner AS t1 ON p1.owner = t1.teear
				LEFT OUTER JOIN tearner AS t2 ON p1.manger = t2.teear
				LEFT OUTER JOIN tearner AS t3 ON p1.arctct = t3.teear
				LEFT OUTER JOIN tearner AS t4 ON p1.delvry = t4.teear
				LEFT OUTER JOIN tearner AS t5 ON p1.teamld = t5.teear
				LEFT OUTER JOIN tearner AS t6 ON p1.testld = t6.teear
				LEFT OUTER JOIN tearner AS t7 ON p1.prodld = t7.teear
				LEFT OUTER JOIN tearner AS t8 ON p1.anlyst = t8.teear
				LEFT OUTER JOIN (SELECT r2.procde AS procde,
									r2.entry,
									r2.rag AS rag,
									r2.summary AS summary,
									r2.notes AS notes
								FROM b6009822.jhcjutil.PROJRAG AS r2
								INNER JOIN (
									SELECT procde,
										max(entry) AS entry
									FROM b6009822.jhcjutil.PROJRAG
									GROUP BY procde
									) AS r3 ON r2.procde = r3.procde AND r2.entry = r3.entry) AS risk ON risk.procde = p1.procde											
			WHERE p1.status = 'ACTIVE'                                 
			  AND r.release_number = ?                            
			  AND r.release_committee_decision = 'APPROVED' 
			  AND p1.closed <> 'Y'
			GROUP BY p1.procde, r.sit_cycle, p1.desc, p1.client, risk.rag, t1.tename, t2.tename, t3.tename, t4.tename, t5.tename, t6.tename, t7.tename, t8.tename, p1.phase, p1.notes
			ORDER BY p1.procde                                         '''

	curs = execute_query(sql, parms = [release, ])		
	data = curs.fetchall()				
		
	projectList = []		
	clientList = []
	projectManagerList = []
	devTeamLeadList = []
	testLeadList = []
	
	for row in data:
	
		project = Project(row)
		projectList.append(project)
		
		if Client(project.client.strip()) not in clientList:
			client = Client(project.client.strip())
			clientList.append(client)

		if ProjectManager(project.projectManager.strip()) not in projectManagerList and project.projectManager.strip() != "":
			projectManager = ProjectManager(project.projectManager.strip())
			projectManagerList.append(projectManager)	

		if DevTeamLead(project.teamLeader.strip()) not in devTeamLeadList and project.teamLeader.strip() != "":
			devTeamLead = DevTeamLead(project.teamLeader.strip())
			devTeamLeadList.append(devTeamLead)
			
		if TestLead(project.testLeader.strip()) not in testLeadList and project.testLeader.strip() != "":
			testLead = TestLead(project.testLeader.strip())
			testLeadList.append(testLead)		
	
	projectManagerList = sorted(projectManagerList, key=lambda projectManager: projectManager.name)
	clientList = sorted(clientList, key=lambda client: client.name)
	
	return render_template("releases/list.html", projectList = projectList, clientList = clientList, filterOptions = filterOptions, projectManagerList = projectManagerList, devTeamLeadList=devTeamLeadList, testLeadList=testLeadList, title="Releases", release=release)
	

app/revenue/views.py
from flask import Blueprint, render_template, request, url_for, redirect, flash
import json

from app.revenue.forms import RevenueForm
from app.revenue.api import *

mod = Blueprint('revenue', __name__, url_prefix='/revenue/')
	
@mod.route('/')
def detail():
	
	return render_template("revenue/detail.html", title="Revenue", revenueList = getAllRevenueEntries())	
	
@mod.route('summarybymonth')
def summaryByMonth():
	
	return render_template("revenue/summary_by_month.html", title="Revenue", revenueSummaryList = getSummaryByMonth())		
	
@mod.route('summarybyyear')
def summaryByYear():
	
	return render_template("revenue/summary_by_year.html", title="Revenue", revenueSummaryList = getSummaryByYear())	
	
@mod.route('add', methods=['GET','POST'])
def add():

	form = RevenueForm()
	
	if request.method == 'POST' and form.validate():
	
		client = form.client.data
		project = form.project.data
		year = form.year.data
		month = form.month.data
		value = form.value.data
			
		createRevenueEntry(client, project, year, month, value)
		flash('Created', 'success')	
		return redirect(url_for('revenue.detail'))
	
	return render_template("miForm.html", title="Revenue", form=form)		
	

app/templates/base.html
<html>

	<head>
		<title>{% if title %}{{title}}{% else%}Internal Tools{% endif %}</title>
		<link rel="stylesheet" type=text/css href="{{ url_for('static', filename='bootstrap.min.css') }}">
		<link rel="stylesheet" type=text/css href="{{ url_for('static', filename='css.css') }}">
		<link rel="stylesheet" type=text/css href="http://cdn.datatables.net/1.10.7/css/jquery.dataTables.css">
		<link rel="stylesheet" type=text/css href="//cdn.datatables.net/tabletools/2.2.4/css/dataTables.tableTools.css">
		<link rel="shortcut icon" href="{{ url_for('static', filename='jhc.ico') }}">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>  
		<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>		
		<script src="http://cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
		<script src="{{ url_for('static', filename='jquery.dataTables.columnFilter.js') }}"></script>		
	</head>

	<body>

		<div class="navbar navbar-default navbar-fixed-top" >
			<div class="navbar-inner">		
				<div class="nav-collapse">
					<ul class="nav navbar-nav">
						<li><a href="{{ url_for('releases.overview')}}">Releases</a></li>
						<li><a href="{{ url_for('search.overview')}}">Search</a></li>
						<li><a href="{{ url_for('files.overview')}}">Files</a></li>
					</ul>
				</div>			
			</div>
		</div>

		<div class="navbar navbar-default" >
		</div>
		
<div>
  {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
            {% if category == 'message' %}
              <div class="alert alert-warning" role="alert">
            {% else %}
              <div class="alert alert-{{ category }}" role="alert">
            {% endif %}
              {{ message }}
            </div>
        {% endfor %}
      {% endif %}
  {% endwith %}
</div>
		
		{% block content %}{% endblock %}
	
	</body>
</html>

app/templates/files-main.html
{% extends "files-base.html" %}{% block content %}
	
	{% with messages = get_flashed_messages() %}{% if messages %}
		<ul class="flashes alert alert-danger">{% for message in messages %}
			<li>{{ message }}</li>{% endfor %}
		</ul>{% endif %}
	{% endwith %}		
	
		<table id="main_table" class="table table-striped table-hover">
		
			<thead>
			  <tr>  
				{% for column in columns %}<th>{{column}}</th>{% endfor %}
			  </tr>
			</thead>	
			
			<tfoot>
			  <tr>  
				{% for column in columns %}<td>{{column}}</td>{% endfor %}
			  </tr>
			</tfoot>
			
			<tbody >

			</tbody>

		</table>

	
	<script> 
			$(document).ready(function() {
			var oTable = $('#main_table').dataTable( {
				"processing": true,
				"serverSide": true,
				"bStateSave": true,
				"dom": '<"top"ip><"right"lT>rt<"bottom"><"clear">',
				"sPaginationType": "full_numbers",
				"sScrollX": "100%",
				"tableTools": {"sSwfPath": "{{ url_for('static', filename='copy_csv_xls_pdf.swf') }}", "aButtons": [ "copy", "csv" ]},
				"sAjaxSource": "{{url_for('get_data', library = library, table = table)}}"
			} ).columnFilter({"bUseColVis": true});
			
			oTable.fnSetColumnVis( 0, false );
			oTable.fnSetColumnVis( 1, false );
			
			$('.text_filter').attr("value", "");
			$('.search_init').attr("value", "");
			
		} );		
	</script>
{% endblock %}	

app/templates/jobs-history.html
{% extends "base.html" %}

{% block menu %}
	<li><a href="{{url_for('overview')}}">Overview</a></li>
	<li><a href="{{url_for('job_list')}}">Job List</a></li>
	<li><a href="{{url_for('history')}}">History</a></li>
{% endblock %}

{% block content %}

<h2>Open Job Count History (P1/P2)</h2>

<div id="jobhistory" class="jobhistory"></div>
<div class="loader"></div>

<script type="text/javascript">
    google.load('visualization', '1.1', {packages: ['corechart']});
    google.setOnLoadCallback(drawChart);

	function drawChart() {

		$.ajax({
			url: "/jobs/history_chart",
			dataType: "json",
			success: function (json) {

				for (var i = 0; i < json.rows.length; i++) {
					json.rows[i].c[0].v = new Date(json.rows[i].c[0].v.substring(0,4), Number(json.rows[i].c[0].v.substring(5,7)) - 1, json.rows[i].c[0].v.substring(8,10)) ; 
				};
				
				var data = new google.visualization.DataTable(json);

				var options = {
					chart: {
					  title: 'FST Job History'
					},
					backgroundColor: { fill:'transparent' },
					width: $( window ).width,
					height: $( window ).height,
					series: { 0: { color: '#ff6c00' } },
					hAxis: { textStyle:{color: 'white'}, baselineColor: 'white', gridlineColor: 'white'},
					vAxis: { textStyle:{color: 'white'}, baselineColor: 'white', gridlineColor: 'white'},
					legend:{textStyle:{color: 'white'}},
				};

				var chart = new google.visualization.LineChart(document.getElementById('jobhistory'));

				$(".loader").hide();
				
			  chart.draw(data, options);
						}
		});
	}	
  </script>		

{% endblock %}

app/templates/jobs-list.html
{% extends "base.html" %}

{% block menu %}
	<li><a href="{{url_for('overview')}}">Overview</a></li>
	<li><a href="{{url_for('job_list')}}">Job List</a></li>
	<li><a href="{{url_for('history')}}">History</a></li>
{% endblock %}

{% block content %}

		<div class="filter container">
			<form class="form-inline">
			  	<div class="form-group">
			    	<label for="priority">Priority</label>
			    	<select class="form-control" id="priority">
					  	<option>All</option>
					  	<option {% if filterOptions.priority == "P1" %}selected {% endif %}>P1</option>
					  	<option {% if filterOptions.priority == "P2" %}selected {% endif %}>P2</option>
					  	<option {% if filterOptions.priority == "P3" %}selected {% endif %}>P3</option>
					  	<option {% if filterOptions.priority == "P4" %}selected {% endif %}>P4</option>
					  	<option {% if filterOptions.priority == "P5" %}selected {% endif %}>P5</option>
					</select>
			  	</div>
			  	<div class="form-group">
			    	<label for="client">Client</label>
			    	<select class="form-control" id="client" value="{{filterOptions.client}}">
			    		<option>All</option>
						{% for client in clientList %}<option {% if client.name == filterOptions.client %}selected {% endif %}>{{client.name}}</option>{% endfor %}  	  	
					</select>
			  	</div>
			  	<div class="form-group">
			    	<label for="assignedto">Assigned To</label>
			    	<input type="text" class="form-control" id="assignedto" placeholder="Assigned To" value="{{filterOptions.assignedTo}}">
			  	</div>	
			  	<div class="form-group">
			    	<label for="jobtext">Job Text</label>
			    	<input type="text" class="form-control" id="jobtext" placeholder="Job Text" value="{{filterOptions.jobText}}">
			  	</div>	
			  	<div class="form-group">
			    	<label for="area">Functional Area</label>
			    	<select class="form-control" id="functionalarea" value="{{filterOptions.functionalArea}}">
			    		<option>All</option>
						{% for functionalArea in functionalAreaList %}<option {% if functionalArea.functionalArea == filterOptions.functionalArea %}selected {% endif %}>{{functionalArea.functionalArea}}</option>{% endfor %}  	  	
					</select>
			  	</div>	
			  	<div class="form-group">
			    	<label for="status">Status</label>
			    	<select class="form-control" id="status" value="{{filterOptions.status}}">
			    		<option>All</option>
						{% for status in statusList %}<option value="{{status.letter}}" {% if status.letter == filterOptions.status %}selected {% endif %}>{{status.name}}</option>{% endfor %}  	  	
					</select>
			  	</div>							
			</form>
		</div>

		<div class="container">
			<div class="panel-group" id="accordion">

				{% for job in jobList %}				
			  	<div class="panel panel-default" onclick="loadJobText({{job.number}})">
			  		<a data-toggle="collapse" data-parent="#accordion" href="#J{{job.number}}">
				    	<div class="panel-heading" role="tab">
					      	<h4 class="panel-title">					        	
					          		<span class="paneljobnumber">{{job.number}}</span> - <span class="panelshorttext">{{job.shortText}}</span><span class="panelpriority">P{{job.priority}}</span> 				        	
					      	</h4>
							<p>{{job.longText}}</p>
				    	</div>
			    	</a>
				    <div id="J{{job.number}}" class="panel-collapse collapse" role="tabpanel">
				    	<span class="paddedspan">Client: </span><span>{{job.client}}</span>
				    	<span class="paddedspan">Assigned To: </span><span class="panelassignedto">{{job.assignedTo}}</span>
						<span class="paddedspan">Functional Area: </span><span class="panelfunctionalarea">{{job.functionalArea}}</span>
						<span class="paddedspan">Status: </span><span class="panelstatus">{{job.status}}</span>
				      	<div class="panel-body panellongtext" id="JT{{job.number}}">
				        	
				      	</div>
				    </div>
			  	</div>			  	
				{% endfor %}  

			</div>
		</div>			

		<script type="text/javascript">

			function loadJobText(jobNumber) {
			   $( "#JT" + jobNumber ).load( "{{url_for('job_detail')}}/" + jobNumber);
			};
		
		    function changeUrl(page, url) {
		        var obj = { Page: page, Url: url };
		        history.replaceState(obj, obj.Page, obj.Url);
		    }

			$.expr[":"].containsNoCase = function(el, i, m) {
			    var search = m[3];
			    if (!search) return false;
			    return new RegExp(search, "i").test($(el).text());
			};

			function filterList() {

				var priority = $("#priority").val();
				var client = $("#client").val();
				var assignedTo = $("#assignedto").val();
				var jobText = $("#jobtext").val();
				var functionalArea = $("#functionalarea").val();
				var status = $("#status").val();

				if (priority == "All") {priority = null};
				if (client == "All") {client = null};
				if (functionalArea == "All") {functionalArea = null};
				if (status == "All") {status = null};

		        $(".panel").show();

		        var queryString = '';

		        if (priority) {$(".panelpriority").not(":containsNoCase(" + priority + ")").parent().parent().parent().parent().hide();	queryString = queryString + '&priority=' + priority;};
		        if (client) {$(".panelclient").not(":containsNoCase(" + client + ")").parent().parent().hide();	queryString = queryString + '&client=' + client;};	
		        if (assignedTo) {$(".panelassignedto").not(":containsNoCase(" + assignedTo + ")").parent().parent().hide();	queryString = queryString + '&assignedto=' + assignedTo;};	
		        if (jobText) {$(".panelshorttext").not(":containsNoCase(" + jobText + ")").parent().parent().parent().parent().hide();	queryString = queryString + '&jobtext=' + jobText;};
		        if (functionalArea) {$(".panelfunctionalarea").not(":containsNoCase(" + functionalArea + ")").parent().parent().hide();	queryString = queryString + '&functionalarea=' + functionalArea;};
		        if (status) {$(".panelstatus").not(":containsNoCase(" + status + ")").parent().parent().hide();	queryString = queryString + '&status=' + status;};					

		        if (queryString.length > 1) {queryString = '?' + encodeURIComponent(queryString.substring(1))} else {queryString = '?'};

		        changeUrl('Jobs 5', queryString);

			}

			$("#priority").change(function() { filterList() });
		    $("#client").change(function() { filterList() });
			$("#assignedto").keyup(function() { filterList() });
			$("#jobtext").keyup(function() { filterList() });
			$("#functionalarea").change(function() { filterList() });
			$("#status").change(function() { filterList() });

			$( document ).ready(filterList());

		</script>

{% endblock %}

app/templates/jobs-overview.html
{% extends "base.html" %}

{% block menu %}
	<li><a href="{{url_for('overview')}}">Overview</a></li>
	<li><a href="{{url_for('job_list')}}">Job List</a></li>
	<li><a href="{{url_for('history')}}">History</a></li>
{% endblock %}

{% block content %}
	
		<div class="row">

			<div class="col-md-4"> 			
				<table class="table table-bordered table-responsive tablejobs">
					<caption>Jobs By Priority</caption>
					<thead>
						<tr>
							<th>Priority</th>
							<th>Number of Jobs</th>
						</tr>
					</thead>
					<tbody>
						{% for priority in priorityList %}
						<tr data-href="{{url_for('job_list', priority = 'P' + priority.level)}}">
							<td>P{{priority.level}}</td>
							<td>{{priority.numberOfJobs}}</td>
						</tr>
						{% endfor %}						
					<tbody>
					<tfoot>
						<tr>
							<td>Total</td>
							<td>{{total}}</td>
						</tr>
					</tfoot>
				</table>

			</div>
			
			<div class="col-md-4">
			
				<table class="table table-bordered table-responsive tablejobs">
					<caption>Jobs By Status</caption>
					<thead>
						<tr>
							<th>Status</th>
							<th>Number of Jobs</th>
						</tr>
					</thead>
					<tbody>
						{% for status in statusList %}
						<tr data-href="{{url_for('job_list', status = status.letter)}}">
							<td>{{status.name}} </td>
							<td>{{status.numberOfJobs}} </td>
						</tr>	
						{% endfor %}
					<tbody>
					<tfoot>
					</tfoot>
				</table>			
			
			</div>			

			<div class="col-md-4">
			
				<table class="table table-bordered table-responsive tablejobs">
					<caption>Jobs By Time Period</caption>
					<tbody>
						<tr class="nohover">
							<td>Opened This Month</td>
							<td>{{monthlyJobsOpened}} </td>
						</tr>	
						<tr class="nohover">
							<td>Closed This Month</td>
							<td>{{monthlyJobsClosed}} </td>
						</tr>	
						<!--<tr class="nohover">
							<td>Average Resolution This Month</td>
							<td>{{monthlyAverageResolution}} </td>
						</tr>	-->						
						<tr class="nohover">
							<td>Opened This Quarter</td>
							<td>{{quarterlyJobsOpened}} </td>
						</tr>	
						<tr class="nohover">
							<td>Closed This Quarter</td>
							<td>{{quarterlyJobsClosed}} </td>
						</tr>	
						<!--<tr class="nohover">
							<td>Average Resolution This Quarter</td>
							<td>{{quarterlyAverageResolution}} </td>
						</tr>-->						
					<tbody>
				</table>			
		
			</div>			
			
		</div>		
		
		<div class="row">
			<div class="col-md-4" id="jobsByClient"></div>
			<div class="col-md-4" id="jobsByPriority"></div>
			<div class="col-md-4" id="jobsByArea"></div>		
		</div>

<script>
clickableRowListener = function(that, e) {
    var url = $(that).parent().data("href") || $(that).parent().find("a").attr("href");
    if (url) {window.open(url,"_self")}
        
    };

 
// Onload: Add eventlistener
$('tr td').on('mousedown', function (e) {
    clickableRowListener(this, e);
});


var jobsByArea = new d3pie("jobsByArea", {
	"header": {"title": {"text": "Jobs By Area","color": "#ff6c00","fontSize": 24,"font": "Lucida Sans Unicode"}, 
	         "location": "top-center"},
	"size": {"canvasWidth": $( window ).width()/3.5,"pieInnerRadius": "25%","pieOuterRadius": "100%"},
	"data": {"sortOrder": "value-desc","smallSegmentGrouping": {"enabled": true,"value": 3},
		     "content": [{% for area in areaList %}{"label": "{{area.functionalArea}}","value": {{area.numberOfJobs}} },{% endfor %} ]},
	"labels": {"outer": {"format": "none"},
		       "inner": {"format": "label", "hideWhenLessThanPercentage": 3},
		       "mainLabel": {"color": "#ffffff","fontSize": 16},
		       "percentage": {"color": "#ffffff","decimalPlaces": 0},
		       "value": {"color": "#adadad","fontSize": 16},
		       "lines": {"enabled": true}},
	"tooltips": {"enabled": true,"type": "placeholder","string": "{value}"},
	"effects": {"pullOutSegmentOnClick": {"effect": "linear","speed": 400,"size": 8}},
	"misc": {"gradient": {"enabled": true,"percentage": 100}, "colors": {"segmentStroke": "#0a2d41"}},
	"callbacks": { onClickSegment: function(a) {window.open("/jobs/joblist?functionalarea=" + a.data.label,"_self");}}
});

var jobsByPriority = new d3pie("jobsByPriority", {
	"header": {"title": {"text": "Jobs By Priority","color": "#ff6c00","fontSize": 24,"font": "Lucida Sans Unicode"},
	           "location": "top-center"},
	"size": {"canvasWidth": $( window ).width()/3.5, "pieInnerRadius": "25%","pieOuterRadius": "100%"},
	"data": {"sortOrder": "label-asc","smallSegmentGrouping": {"enabled": false,"value": 10},
		     "content": [{% for priority in priorityList %}{"label": "P{{priority.level}}","value": {{priority.numberOfJobs}} },{% endfor %} ]},
	"labels": {"outer": {"format": "none"},
		       "inner": {"format": "label", "hideWhenLessThanPercentage": 3},
		       "mainLabel": {"color": "#ffffff","fontSize": 16},
		       "percentage": {"color": "#ffffff","decimalPlaces": 0},
		       "value": {"color": "#adadad","fontSize": 16},
		       "lines": {"enabled": true}},
	"tooltips": {"enabled": true,"type": "placeholder","string": "{value}"},
	"effects": {"pullOutSegmentOnClick": {"effect": "linear","speed": 400,"size": 8}},
	"misc": {"gradient": {"enabled": true,"percentage": 100}, "colors": {"segmentStroke": "#0a2d41"}},
	"callbacks": { onClickSegment: function(a) {window.open("/jobs/joblist?priority=" + a.data.label,"_self");}}
});

var jobsByClient = new d3pie("jobsByClient", {
	"header": {"title": {"text": "Jobs By Client","color": "#ff6c00","fontSize": 24,"font": "Lucida Sans Unicode"},
	           "subtitle": {"text": " ", "color": "#0a2d41","fontSize": 14,"font": "arial"}, "location": "top-center", "titleSubtitlePadding": 4},
	"size": {"canvasWidth": $( window ).width()/3.5,"pieInnerRadius": "25%","pieOuterRadius": "100%"},
	"data": {"sortOrder": "value-desc","smallSegmentGrouping": {"enabled": true,"value": 3},
		     "content": [{% for client in clientList %}{"label": "{{client.name}}","value": {{client.numberOfJobs}} },{% endfor %} ]},
	"labels": {"outer": {"format": "none"},
		       "inner": {"format": "label", "hideWhenLessThanPercentage": 3},
		       "mainLabel": {"color": "#ffffff","fontSize": 16},
		       "percentage": {"color": "#ffffff","decimalPlaces": 0},
		       "value": {"color": "#adadad","fontSize": 16},
		       "lines": {"enabled": true}},
	"tooltips": {"enabled": true,"type": "placeholder","string": "{value}"},
	"effects": {"pullOutSegmentOnClick": {"effect": "linear","speed": 400,"size": 8}},
	"misc": {"gradient": {"enabled": true,"percentage": 100}, "colors": {"segmentStroke": "#0a2d41"}},
	"callbacks": { onClickSegment: function(a) {window.open("/jobs/joblist?client=" + a.data.label,"_self");}}
});


 function autoRefresh()
{
	   window.location.reload();
}
 
 setInterval('autoRefresh()', 300000); // this will reload page after every 5 minutes

</script>

{% endblock %}

app/templates/knowledge-overview.html
{% extends "base.html" %}{% block content %}
	

{% endblock %}

app/templates/miBase.html
<html>

	<head>
		<title>{% if title %}{{title}}{% else%}Internal Tools{% endif %}</title>
		<link rel="stylesheet" type=text/css href="{{ url_for('static', filename='bootstrap.min.css') }}">
		<link rel="stylesheet" type=text/css href="{{ url_for('static', filename='css.css') }}">
		<link rel="shortcut icon" href="{{ url_for('static', filename='jhc.ico') }}">
		<link rel="stylesheet" type=text/css href="https://cdn.datatables.net/1.10.11/css/jquery.dataTables.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>  
		<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>	
		<script src="https://cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js"></script>		
	</head>

	<body>

		<div class="navbar navbar-default navbar-fixed-top" >
			<div class="navbar-inner">		
				<div class="nav-collapse">
					<ul class="nav navbar-nav">
						<li><a href="{{ url_for('revenue.detail')}}">Detail</a></li>
						<li><a href="{{ url_for('revenue.summaryByMonth')}}">Summary By Month</a></li>
						<li><a href="{{ url_for('revenue.summaryByYear')}}">Summary By Year</a></li>
					</ul>
				</div>			
			</div>
		</div>

		<div class="navbar navbar-default" >
		</div>
		
		<div>
		  {% with messages = get_flashed_messages(with_categories=true) %}
			  {% if messages %}
				{% for category, message in messages %}
					{% if category == 'message' %}
					  <div class="alert alert-warning" role="alert">
					{% else %}
					  <div class="alert alert-{{ category }}" role="alert">
					{% endif %}
					  {{ message }}
					</div>
				{% endfor %}
			  {% endif %}
		  {% endwith %}
		</div>
		
		{% block content %}{% endblock %}
	
	</body>
</html>

app/templates/miForm.html
{% extends "miBase.html" %}
{% from 'macros.html' import render_form %}
{% block content %}

<div class="col-lg-6">

  {{ render_form(form, action_url='', action_text='Submit') }}

</div>

{% endblock %}